(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var E4=function(a){a.ma("cardstatechange",a.Ai()&&a.xm()?1:0)},F4=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},v1a=function(a){var b=g.Hl(a);
a=g.Kl(a);return new g.wl(b.x,b.y,a.width,a.height)},w1a=function(a){return Math.pow(a,3)},x1a=function(a){return 3*a*a-2*a*a*a},I4=function(a){a=g.Oa(a);
delete G4[a];g.vf(G4)&&H4&&H4.stop()},z1a=function(){H4||(H4=new g.Xn(function(){y1a()},20));
var a=H4;a.isActive()||a.start()},y1a=function(){var a=g.Ra();
g.lf(G4,function(b){A1a(b,a)});
g.vf(G4)||z1a()},J4=function(a,b,c,d){g.ro.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},A1a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;B1a(a,a.progress);1==a.progress?(a.j=0,I4(a),a.onFinish(),a.Vz()):a.Tc()&&a.tF()},B1a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},C1a=function(a,b){g.af.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},K4=function(a,b,c,d,e){J4.call(this,b,c,d,e);
this.element=a},D1a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
K4.call(this,a,b,c,d,e)},L4=function(a){g.J.call(this);
this.u=a||window;this.j=[]},M4=function(a){return a.baseUrl||null},N4=function(a,b){return g.um(g.Ok(a,b),function(c){return!!c})},E1a=function(a,b,c){function d(X){var Q=X.hovercardButton;
if(!Q)return null;Q=Q.subscribeButtonRenderer;if(!Q)return null;var oa=f(Q.unsubscribedButtonText),sa=f(Q.subscribedButtonText);if(Q.subscribed){var Ba=f(Q.subscriberCountWithUnsubscribeText);var ya=f(Q.subscriberCountText)}else Ba=f(Q.subscriberCountText),ya=f(Q.subscriberCountWithSubscribeText);var va=null;if(X.signinEndpoint){va=F4(X,"signinEndpoint","webNavigationEndpointData","url");if(!va){var Ja,Ka,qa;va=null==(Ja=Q.signInEndpoint)?void 0:null==(Ka=Ja.commandMetadata)?void 0:null==(qa=Ka.webCommandMetadata)?
void 0:qa.url}if(!va)return null}return oa&&(sa||va)?{subscribed:Q.subscribed,subscribeText:oa,subscribeCount:Ba,unsubscribeText:sa,unsubscribeCount:ya,enabled:Q.enabled,signinUrl:va,classic:X.useClassicSubscribeButton}:null}
function e(X){if(X){var Q=[],oa=X.videoId;oa&&Q.push("v="+oa);(oa=X.playlistId)&&Q.push("list="+oa);(X=X.startTimeSeconds)&&Q.push("t="+X);return"/watch?"+Q.join("&")}}
function f(X){if(!X)return null;var Q=X.simpleText;return Q?Q:X.runs?g.Ok(X.runs,function(oa){return oa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,u=null,w=null,y=null,A=!1,B=null,D=null,G=null,H=null,L=null,N=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(N=l.watchEndpoint,m=e(N)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,u=f(p.text),p="LIVE"===p.style):u=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(N=l.watchEndpoint,m=e(N)),n=!1,q=a,w=f(b.playlistLength);
else if("CHANNEL"===h){if(A=F4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?B=d(b):D=f(b.subscribersText)}else"WEBSITE"===h?((G=F4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=F4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=F4(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:
null,P="";if(b.metadata){var R=f(b.metadata);R&&(P=R)}return{id:"element-"+c,type:h,title:f(b.title),metadata:P,callToAction:f(b.callToAction),GO:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:u,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:D,isSubscribe:A,targetUrl:m||null,s_:n,sessionData:K?{itct:K}:null,L5:q,Ux:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:N4(b.impressionUrls||[],M4),d_:N4(b.hovercardShowUrls||[],M4),clickUrls:N4(l.loggingUrls||[],M4),visualElement:g.sz(b.trackingParams),productPrice:H,additionalFeesText:L,watchEndpoint:N||null}},F1a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:N4(a.impressionUrls||[],M4),elements:N4(a.elements||[],function(d,e){return E1a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.sz(a.trackingParams));return c},G1a=function(a){g.eO.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Z=!0;this.I=0;a=a.V();this.S=g.QF(a)||g.UF(a);this.ea=a.experiments.jb("web_rounded_thumbnails");this.events=new g.XD(this);g.M(this,this.events);this.events.T(this.player,g.sA("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.tA("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Cb);this.events.T(window,"focus",this.O3);this.load();var b=g.hh("STYLE");(g.$g("HEAD")[0]||
document.body).appendChild(b);g.$e(this,function(){g.oh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},H1a=function(a){return a.player.getVideoData().C?"current":a.S?"new":"current"},O4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},I1a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=F1a(f,H1a(a))));P4(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.ir;d&&(c.postParams={ad_tracking:d});if(b=g.TBa(b))if(b=g.pg(b),b=g.og(b))a.B=g.Au(b,c)},P4=function(a,b,c){c=void 0===c?!0:c;
a.player.Gf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&J1a(a);c=[];d=new g.qA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.W({F:"div",N:"ytp-ce-shadow"}),g.BN(a.player,a.u.element,4),a.C=new g.IL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=K1a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.BN(a.player,f.element,4);var h=new g.qA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);L1a(a,
f,e)}else g.pz(new g.Pv("buildEndscreenElement null",e))}a.player.qe(c);a.Cb()}},J1a=function(a){var b=g.yz(),c=g.zz();
c&&b&&a.endscreen.visualElement&&g.Dz(void 0,c,b,[a.endscreen.visualElement])},K1a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Fa:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.Ux||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:Q4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:R4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Fa:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.vo(b.title||"")},oa:b.title},{F:"div",N:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
oa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Fa:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.Ux||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-covering-image",X:Q4(b)},{F:"div",N:"ytp-ce-covering-shadow-top"},{F:"a",N:"ytp-ce-covering-overlay",X:{href:R4(a,b.targetUrl),tabindex:"-1"},W:[{F:"div",Fa:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.vo(b.title||"")},oa:b.title},{F:"div",N:"ytp-ce-playlist-count",
W:[{F:"div",N:"ytp-ce-playlist-icon"},{F:"div",N:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Fa:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.Ux||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"a",Fa:["ytp-ce-channel-title","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.vo(b.title||"")},oa:b.title},b.subscribeButton?{F:"div",N:"ytp-ce-subscribe-container",W:[{F:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",N:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{F:"div",Fa:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:Q4(b)}]};c=new g.W(c);var d=g.ah(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.fo(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.iP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Fa:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.Ux||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},{F:"div",N:"ytp-ce-expanding-overlay-content",
W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-website-title",X:{dir:g.vo(b.title||"")},oa:b.title},{F:"div",N:"ytp-ce-website-metadata",oa:b.metadata},{F:"a",Fa:["ytp-ce-website-goto","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:Q4(b)},{F:"div",N:"ytp-ce-expanding-icon",X:M1a(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",N:"ytp-ce-merchandise-price-container",W:[{F:"div",N:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.W.push({F:"div",N:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={F:"div",Fa:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.Ux||"","aria-hidden":"true"},W:[{F:"div",N:"ytp-ce-element-shadow"},{F:"div",N:"ytp-ce-expanding-overlay",W:[{F:"div",N:"ytp-ce-expanding-overlay-hider"},{F:"div",N:"ytp-ce-expanding-overlay-background"},
{F:"div",N:"ytp-ce-expanding-overlay-content",W:[{F:"div",N:"ytp-ce-expanding-overlay-body",W:[{F:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{F:"div",N:"ytp-ce-merchandise-title",X:{dir:g.vo(b.title||"")},oa:b.title},c,{F:"div",N:"ytp-ce-merchandise-metadata",oa:b.metadata},{F:"a",Fa:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:R4(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{F:"div",N:"ytp-ce-expanding-image",X:Q4(b)},{F:"div",N:"ytp-ce-merchandise-invideo-cta-container",
W:[{F:"div",N:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.fo(c.element,"ytp-ce-placeholder");return c},Q4=function(a){if(a.GO)var b=a.GO.thumbnails;
return M1a(b?b[b.length-1].url:null)},M1a=function(a){return a?{style:"background-image: url("+a+")"}:{}},L1a=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.Z&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.fo(b.element,"ytp-ce-force-expand"),S4(a,c.id,!0)):(g.ho(b.element,"ytp-ce-force-expand"),g.ho(b.element,"ytp-ce-element-hover"),S4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){N1a(a,b,c)});
b.Ra("mouseleave",function(){O1a(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.fo(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){P1a(a,c,m)});
b.Ra("keypress",function(m){P1a(a,c,m)});
b.Ra("focus",function(){N1a(a,b,c)});
b.Ra("blur",function(){O1a(a,b,c)});
b.Ra("touchstart",function(){N1a(a,b,c)});
var l=g.ch("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.ho(b.element,"ytp-ce-element-hover");g.ho(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.Z=9===m.keyCode&&!m.shiftKey});
d(g.ch("ytp-sb-subscribe",b.element));d(g.ch("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},P1a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.eo(d,"ytp-ce-element");){g.eo(d,"subscribe-label")&&Q1a(a,b);
if(g.eo(d,"ytp-ce-channel-subscribe"))return;d=g.ph(d)}if(!d||g.eo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])O1a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.L5)Q1a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.pg(R4(a,b.targetUrl)),g.iM(g.og(c),void 0,b.sessionData);else{var e=g.jG(a.player.V())||a.player.getVideoData().C,f=function(){var h=R4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.lu(h);e&&n&&(n.v||
n.list)?a.player.Nl(n.v,l,n.list,!1,void 0,m||void 0):g.hM(h,l)};
Q1a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},R4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.tG(a)+b}else return"";return b},N1a=function(a,b,c){g.eo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.fo(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.Xn(function(){g.fo(b.element,"ytp-ce-element-hover")},200)).start():g.fo(b.element,"ytp-ce-element-hover"),T4(a,c.d_),S4(a,c.id,!0))},O1a=function(a,b,c){g.ho(b.element,"ytp-ce-element-hover");
g.ho(b.element,"ytp-ce-force-expand");S4(a,c.id,!1)},S4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.jo(a.j[e].element,"ytp-ce-element-shadow-show",c)},T4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||O4(a))c&&c();else{b=R1a(a,b);var e=0,f=!1,h=new g.Xn(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Uw(b[a],d)}},Q1a=function(a,b,c){T4(a,b.clickUrls,c);
(a=g.zz())&&b.s_&&g.Jz(a,b.visualElement)},R1a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(S1a(b[d],c));return a},S1a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},T1a=function(a){return"string"===typeof a?a:""},U4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},U1a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},V4=function(a){return a.value?a.value:null},W4=function(a){if(!a)return null;
var b=g.pg(T1a(a.value));b=g.og(b);if(!b)return null;var c=U4(a.target,V1a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new U1a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},W1a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Z1a=function(a){if(!a)return null;
var b=U4(a.type,X1a),c=U4(a.trigger,Y1a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=W4(a?a:null);return b?new W1a(b,c,a):null},$1a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},a2a=function(a,b){return g.Pb(a.action,b)},b2a=function(a,b){this.context=a;
this.j=b},c2a=function(a){return a.customMessage?X4("div","iv-card-message",a.customMessage):""},Y4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",N:"iv-card-image",X:{style:a},W:c}},d2a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(X4("li","",c.value));return{F:"ul",N:"iv-card-meta-info",W:b}},X4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.vo(c);return{F:a,X:b,oa:c}},e2a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.iy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.iy+");");c.dir=g.vo(a.customMessage);var d=[{F:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",N:"iv-card-link-icon"}));return{F:"div",Fa:b,X:c,W:d}},Z4=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},f2a=function(a,b){this.merchant=a;
this.price=b},g2a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},h2a=function(a,b){return b?b:g2a(a)?"current":"new"},$4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.yb=!1;this.Ya=new Map;this.eb=new Map;this.context.G.addEventListener(g.sA("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.tA("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)})},a5=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.uF(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.yb=!1});
a.context.j.Ra(b,"touchmove",function(){a.yb=!0})},i2a=function(a){var b;
return(null==(b=g.Zu(a,g.PH))?0:b.url)?g.Zu(a,g.PH).url:(a=g.Zu(a,g.TG))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},b5=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
SS:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
HE:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},j2a=function(a,b,c){$4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Qa=this.Rb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.Gb=this.S=this.La=this.D=this.Wa=this.j=null;this.ea=[];this.qa=this.J=this.sf=this.Ia=null;this.I=0;this.Ba=new g.Xn(function(){},c.Y.kf?4E3:3E3);
g.M(this,this.Ba);this.ob=new g.Xn(function(){});
g.M(this,this.ob);this.Aa=new b2a(c,function(e,f,h,l,m,n){a5(d,e,f,h,l,m,n)});
this.Z=new g.W({F:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{F:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{F:"span",N:"iv-drawer-header-text"},{F:"button",Fa:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Ocultar cards",tabindex:"0"}}]},{F:"div",N:"iv-drawer-content"}]});g.M(this,this.Z);this.C=this.Z.element;this.kb=new g.IL(this.Z,330);g.M(this,this.kb);this.Lb=g.ch("iv-drawer-header-text",this.C);this.u=g.ch("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Rb&&c5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Rb=d.B)&&d5(d)});
this.G.addEventListener("videodatachange",this.Zp.bind(this))},k2a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){c5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){d5(a)});
var c=b.headerText;g.rh(a.Lb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.sz(b.trackingParams);a.J=g.sz(b.closeTrackingParams);a.sf=g.sz(b.iconTrackingParams)},l2a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.V().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.xA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},ym:null,Fj:e.trackingParams?g.sz(e.trackingParams):null,sf:f&&f.trackingParams?g.sz(f.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,iy:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};e5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.xA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,f),sponsored:!1,tracking:b5(f,e,f.command),ym:f.trackingParams?g.sz(f.trackingParams):null,Fj:e.trackingParams?g.sz(e.trackingParams):null,sf:l&&l.trackingParams?g.sz(l.trackingParams):null,imageUrl:g5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.xA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,iy:null,title:f.title?g.xA(f.title):"",customMessage:f.callToAction?g.xA(f.callToAction):"",url:g.Zu(f.command,g.PH).url?W4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Zu(f.command,g.PH).url}):null,onClickCommand:null};e5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.xA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.endpoint),ym:e.trackingParams?g.sz(e.trackingParams):null,Fj:f.trackingParams?g.sz(f.trackingParams):null,sf:l&&l.trackingParams?g.sz(l.trackingParams):null,channelId:g.Zu(e.endpoint,h5).browseId,customMessage:e.customText?g.xA(e.customText):null,profileImageUrl:g5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.xA(e.channelName):"",metaInfo:[e.subscriberCountText?g.xA(e.subscriberCountText):""],url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Zu(e.endpoint,h5).canonicalBaseUrl?g.Zu(e.endpoint,h5).canonicalBaseUrl:"/channel/"+g.Zu(e.endpoint,h5).browseId}),onClickCommand:null};e5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.xA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.action),ym:e.trackingParams?g.sz(e.trackingParams):null,Fj:f.trackingParams?g.sz(f.trackingParams):null,sf:l&&l.trackingParams?g.sz(l.trackingParams):null,LA:g5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.xA(e.customMessage):null,playlistVideoCount:g.xA(e.playlistVideoCount),title:e.playlistTitle?g.xA(e.playlistTitle):"",metaInfo:[e.channelName?
g.xA(e.channelName):"",e.videoCountText?g.xA(e.videoCountText):""],url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:i2a(e.action)}),onClickCommand:null};e5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.xA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:f5(a,c,b,e),sponsored:!1,tracking:b5(e,f,e.action),ym:e.trackingParams?g.sz(e.trackingParams):null,Fj:f.trackingParams?g.sz(f.trackingParams):null,sf:l&&l.trackingParams?g.sz(l.trackingParams):null,LA:g5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.xA(e.lengthString):null,customMessage:e.customMessage?g.xA(e.customMessage):null,title:e.videoTitle?g.xA(e.videoTitle):"",metaInfo:[e.channelName?
g.xA(e.channelName):"",e.viewCountText?g.xA(e.viewCountText):""],isLiveNow:!!e.badge,url:W4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:i2a(e.action)}),onClickCommand:null};e5(a,b)}}}}}a.I++},g5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},f5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},n2a=function(a,b){if(b=m2a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.oh(b.PG),g.Xb(a.cards,b),a.OB(),i5(a)},c5=function(a,b,c){if(!a.B){a.kb.show();
a.Wa=new g.Xn(function(){g.fo(a.context.G.getRootNode(),g.uT.IV_DRAWER_OPEN)},0);
a.Wa.start();a.ya=g.yx(a.u,"mousewheel",function(h){a.Ba.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.zz();d&&a.Ia&&a.J&&g.Hz(d,[a.Ia,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.pQ||(f.pQ=!0,o2a(a.context.logger,f.card.tracking.impression,b)),d&&g.Hz(d,[f.card.ym]);E4(a.G);c&&(a.D=new g.Xn(function(){a.La=a.S;a.Gb.focus()},330),a.D.start())}},d5=function(a){a.B&&(a.kb.hide(),g.zx(a.ya),a.ya=null,g.ho(a.context.G.getRootNode(),g.uT.IV_DRAWER_OPEN),a.B=!1,E4(a.G),a.D&&a.D.stop(),a.D=new g.Xn(function(){a.La&&(a.La.focus(),a.La=null)},330),
a.D.start())},q2a=function(a){g.go(a.element,[g.uT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.BN(a.G,a.C,5);p2a(a);a.S=g.ch("ytp-cards-button",a.G.getRootNode());a.Gb=g.ch("iv-drawer-close-button",a.C);a.isInitialized=!0},p2a=function(a){var b=g.ch("iv-drawer-close-button",a.C);
a.context.j.Ra(b,"click",a.sY,a);a.context.j.Ra(a.u,"touchend",function(){a.Ba.start()});
a.context.j.Ra(a.u,"scroll",a.LY,a);a.context.u.subscribe("onHideControls",function(){a.Qa=!0});
a.context.u.subscribe("onShowControls",function(){a.Qa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Qa=g.eo(a.G.getRootNode(),"ytp-autohide")});
a.ea.push(g.Sx("iv-button-shown",a.E_,a));a.ea.push(g.Sx("iv-button-hidden",a.D_,a));a.ea.push(g.Sx("iv-teaser-shown",a.CU,a));a.ea.push(g.Sx("iv-teaser-hidden",a.G_,a));a.ea.push(g.Sx("iv-teaser-clicked",a.BU,a))},r2a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.Zu(b.onClickCommand,g.uZa))?void 0:c.targetId)?(a.qa=b,!0):!1},s2a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.Zu(h[0],g.T_a))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}}a.qa=b;return!1},e5=function(a,b){if(!r2a(a,b)||s2a(a,b)){var c=t2a(a,b);
if(c){var d={card:b,PG:c.element,pQ:!1};if(!b.onClickCommand){a.isInitialized||q2a(a);n2a(a,b.id);var e=u2a(a,d);g.gc(a.cards,e,0,d);c.Ca(a.u,e);a.OB()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,i5(a),v2a(a,d),c5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&w2a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){w2a(a,d)}),i5(a))}}},t2a=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{F:"div",N:"iv-card-image-text",oa:b.displayDomain}:void 0;var e=e2a(b);d={F:"div",Fa:["iv-card"],W:[{F:"a",N:"iv-click-target",X:{href:b.url?V4(b.url)||"":""},W:[Y4(b.imageUrl,d),{F:"div",N:"iv-card-content",W:[X4("h2",void 0,b.title),e]}]}]};d=new g.W(d);Z4(c,g.bh("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={F:"div",Fa:["iv-card","iv-card-channel"],W:[{F:"a",Fa:["iv-click-target"],X:{href:V4(b.url)||"","data-ytid":b.channelId},W:[Y4(b.profileImageUrl),
{F:"div",N:"iv-card-content",W:[c2a(b),{F:"h2",N:"iv-card-primary-link",oa:b.title},d2a(b)]}]}]};d=new g.W(d);Z4(c,g.bh("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={F:"div",Fa:["iv-card","iv-card-playlist"],W:[{F:"a",N:"iv-click-target",X:{href:V4(b.url)||""},W:[Y4(b.LA,{F:"div",N:"iv-card-image-overlay",W:[{F:"span",N:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{F:"div",N:"iv-card-content",W:[c2a(b),X4("h2","iv-card-primary-link",b.title),d2a(b)]}]}]};
d=new g.W(d);Z4(c,g.bh("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.Vb(b.offers);d=["iv-card"];e="";var h=e2a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",N:"iv-card-offer-price",oa:h.price}),h.merchant&&f.push({F:"div",N:"iv-card-offer-merchant",oa:h.merchant}),h={F:"div",W:f});f=b.url?V4(b.url)||"":"";d={F:"div",Fa:d,X:{tabindex:"0"},W:[{F:"a",Fa:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",N:"iv-card-content",W:[b.sponsored?{F:"div",N:"iv-card-sponsored",W:["Patrocinado",{F:"div",N:"iv-ad-info-container",W:[{F:"div",N:"iv-ad-info",oa:"{{adInfo}}"},{F:"div",N:"iv-ad-info-icon-container",W:[{F:"div",N:"iv-ad-info-icon"},{F:"div",N:"iv-ad-info-callout"}]}]}]}:"",{F:"a",N:"iv-click-target",X:{href:f},W:[X4("h2",e,b.title),h]}]}]};d=new g.W(d);e=g.hh("span");g.rh(e,"Voc\u00ea v\u00ea este produto porque achamos que ele \u00e9 relevante para o v\u00eddeo. O Google pode ser compensado pelo comerciante.");
d.Wd(e,"adInfo");Z4(c,g.bh("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{F:"span",N:"iv-card-video-duration",oa:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Fa:["yt-badge","yt-badge-live"],oa:"AO VIVO AGORA"}:null;f={F:"div",Fa:["iv-card","iv-card-video"],W:[{F:"a",N:"iv-click-target",X:{href:(null==(h=b.url)?void 0:V4(h))||""},W:[Y4(b.LA,d),{F:"div",N:"iv-card-content",W:[c2a(b),X4("h2","iv-card-primary-link",b.title),d2a(b),e]}]}]};d=new g.W(f);Z4(c,g.bh("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.G.V().experiments.jb("web_rounded_containers")&&g.fo(b.element,"ytp-rounded-info");return b},u2a=function(a,b){if(0===a.cards.length)return 0;
a=g.Rb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},x2a=function(a){return a.j?"productListing"===a.j.card.type:g.Td(a.cards,function(b){return"productListing"===b.card.type})},i5=function(a){g.jo(a.G.getRootNode(),"ytp-cards-shopping-active",x2a(a))},w2a=function(a,b){if(!g.eo(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.zz(),d=a.j?a.j.card.sf:a.sf;
c&&d&&g.Iz(c,[d]);a.j=b;i5(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Rw(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ob.isActive()||((!a.B||!a.Ba.isActive()&&a.Qa)&&v2a(a,b),a.ob.start(910+b.card.teaserDurationMs))}},v2a=function(a,b){a.Z.rb?(b=new J4([0,
a.u.scrollTop],[0,b.PG.offsetTop],600,x1a),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.WK(a.Z,!0),a.u.scrollTop=b.PG.offsetTop,g.WK(a.Z,!1))},j5=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},m2a=function(a,b){return g.Pb(a.cards,function(c){return c.card.id===b})},k5=function(a,b,c){$4.call(this,a,b);
this.annotation=c;this.isActive=!1},y2a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},l5=function(a,b,c){k5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},z2a=function(a,b){var c=void 0===c?0:c;
var d=v1a(b).width;g.Fl(b,d);c=new D1a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,w1a);g.M(a,c);a.context.B.Ra(c,"begin",function(){g.Ll(b,!0)});
c.play()},C2a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Fa:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({F:"div",Fa:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.iP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.Ca(d));var f=a.createElement({F:"div",Fa:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Fa:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ll(h,!1);a.context.Y.K("web_rounded_containers")&&g.fo(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Fa:["branding-context-container-outer"]});l.appendChild(h);g.zl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.Xn(function(){A2a(a,h,l)},500);
g.M(a,a.B);a.context.j.Ra(a.element,"mouseover",function(){B2a(a,h,l,f,b.image_height)});
a.context.j.Ra(a.element,"mouseout",function(){a.B.start()})}},B2a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Kl(b);a.j||(b.style.width=g.El(f.width,!0),c.style.width=g.El(f.width,!0));g.zl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.zl(d,"right","1px");a.C=!0;g.Ll(b,!0);a.D=new g.Xn(function(){g.fo(this.element,"iv-branding-active")},0,a);
a.D.start()}},A2a=function(a,b,c){g.ho(a.element,"iv-branding-active");
a.I=new g.Xn(function(){g.Ll(b,!1);a.j||(c.style.width=g.El(0,!0))},250);
a.I.start();a.C=!1},D2a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},E2a=function(a,b,c){k5.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.Z=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Fa:["iv-promo-contents"]});this.D=new g.Xn(function(){d.j.setAttribute("aria-hidden","true");g.Ll(d.B,!1);g.Ll(d.u,!0)},700,this);
g.M(this,this.D)},G2a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promo\u00e7\u00e3o");a.element.tabIndex=0;var e=a.annotation.ye(),f=b.image_url;if(f){var h=a.createElement({F:"div",Fa:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",N:"iv-promo-video-duration",oa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",N:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),h.appendChild(f));e&&a5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",N:"iv-promo-txt"}),g.Bg(f,V4(e)),a.j=f):a.j=a.createElement({F:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",W:[{F:"strong",
oa:b.text_line_1}]});var m=a.createElement({F:"p",W:[{F:"span",N:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Fa:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Fa:["iv-button","iv-promo-button"],W:[{F:"span",N:"iv-button-content",oa:f}]});var p=a.createElement({F:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&a5(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.fo(a.j,
"iv-click-target");e&&a5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",W:[{F:"span",oa:b.text_line_1}]}),m=a.createElement({F:"p",W:[{F:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Fa:["yt-badge","iv-promo-badge-live"],oa:"AO VIVO AGORA"})),g.fo(a.j,"iv-click-target"),e&&a5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);
p&&a.J.appendChild(p);c=a.createElement({F:"div",N:"iv-promo-actions"});a.u=a.createElement({F:"button",Fa:["iv-promo-expand","ytp-button"]});a.u.title="Expandir";a.context.j.Ra(a.u,"click",function(q){F2a(a,5E3,q)});
c.appendChild(a.u);g.Ll(a.u,!1);a.context.j.Ra(a.element,"mouseover",a.HZ,a);a.context.j.Ra(a.element,"mouseout",a.GZ,a);a.context.j.Ra(a.element,"touchend",function(q){F2a(a,5E3,q)});
a.B=a.createElement({F:"button",Fa:["iv-promo-close","ytp-button"]});a.B.title="Fechar";a.context.j.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.CZ:a.BZ,a);c.appendChild(a.B);g.go(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},F2a=function(a,b,c){c.stopPropagation();
H2a(a);I2a(a,b);a.j.focus()},J2a=function(a){a.isCollapsed||a.S||a.C||(g.fo(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},H2a=function(a){a.D.stop();
a.isCollapsed&&(g.io(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Ll(a.u,!1),g.Ll(a.B,!0))},I2a=function(a,b){a.C||(a.C=g.Mh(function(){K2a(this);
J2a(this)},b,a))},K2a=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},L2a=function(a){this.G=a},o2a=function(a,b,c){b&&(c?m5(a,b.map(function(d){return g.Qn(d,c)})):m5(a,b))},m5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Uw(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},M2a=function(a){g.eO.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new L2a(this.player);this.D=new g.XD(this);this.C=this.Gn=null;this.events=new g.XD(this);this.J=this.j=null;this.S=[];g.M(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ma("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.DU,this);this.subscribe("resize",this.GD,this);this.player.V().qa.subscribe("vast_info_card_add",this.CR,this);g.M(this,this.events);this.Z=this.createElement({F:"div",N:"video-custom-annotations"});this.u=new g.W({F:"div",Fa:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.u);g.BN(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Fa:["ytp-iv-video-content"]});g.M(this,this.B);a=this.createElement({F:"div",N:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Ot()&&this.load();var c=this.createElement({F:"style"});(g.$g("HEAD")[0]||document.body).appendChild(c);g.$e(this,function(){g.oh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},N2a=function(a){a=a.createElement({F:"div",
Fa:["annotation","annotation-type-custom"]});g.Ll(a,!1);return a},O2a=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.WK(a.u,b);g.WK(a.B,b)},P2a=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(P2a(a,e))}return c},T2a=function(a){var b=a.player.getVideoData();
if(b.Ya){var c=a.player.V().qa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.uu(h)&&h.responseXML?h.responseXML:null)&&Q2a(a,h)}};
g.Dv()&&(d.onFinish=R2a(a,d.onFinish));d.postParams={ic_only:"1"};S2a(d,c);g.Au(b.Ya,d)}}},S2a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.jy&&(a.postParams.ic_coll=b.jy);b.UB&&(a.postParams.ic_xml=b.UB);b.QA&&(a.postParams.ic_track=b.QA)},U2a=function(a){var b=new g.W({F:"div"});
g.Ll(b.element,!1);var c=new j2a(a.player,b.element,n5(a));g.M(c,b);b.Ca(a.u.element);c.zA();return c},n5=function(a){if(!a.J){var b=new L4(a);
g.M(a,b);var c=new g.Qj(a);g.M(a,c);a.J=new D2a(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.yg)}return a.J},Q2a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.zz();if(e){var f=g.yz();f&&g.Dz(void 0,e,f,[g.sz(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=P2a(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=U4(f.type,V2a),p=U4(f.style,W2a),q=T1a(f.data),u=0!==q.length?JSON.parse(q):{};var w=f.action;f=Z1a;if(null==w)var y=null;else if(g.La(w)){l=[];for(var A=g.r(w),B=A.next();!B.done;B=A.next()){var D=f(B.value);
D&&l.push(D)}y=l}else{var G=f(w);y=G?[G]:[]}e=m&&n?new $1a(m,n,p,y,u):null}else e=null}catch(R){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=N2a(f),L=null;switch(l.type){case "branding":if(f.player.V().Sc)break;f.u.element.appendChild(H);L=new l5(H,n5(f),l);break;case "promotion":g.BN(f.player,H,4),L=new E2a(H,n5(f),l)}L&&L.zA();if(f=L)g.M(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=U2a(a),g.M(a,a.j));if("card"===e.type){c=a.j;var N=e&&e.data&&e.data.card_type;
f=e.data;if(N)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,SS:l.teaser_impression,HE:l.teaser_click},H=f.tracking_params||{},L=null,N){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ym:H.card?g.sz(H.card):null,Fj:H.teaser?g.sz(H.teaser):null,sf:H.icon?g.sz(H.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
ym:H.card?g.sz(H.card):null,Fj:H.teaser?g.sz(H.teaser):null,sf:H.icon?g.sz(H.icon):null,LA:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "productListing":f.signin_url&&(L=W4({target:"current",value:f.signin_url}));N=[];for(var K=f.offers||[],P=0;P<K.length;P++)N.push(new f2a(g.Ug(K[P].merchant),
g.Ug(K[P].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ym:H.card?g.sz(H.card):null,Fj:H.teaser?g.sz(H.teaser):null,sf:H.icon?g.sz(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),l6a:L,k6a:f.signin_title?f.signin_title:void 0,j6a:f.signin_message?f.signin_message:void 0,offers:N,onClickCommand:null};e5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ym:H.card?g.sz(H.card):
null,Fj:H.teaser?g.sz(H.teaser):null,sf:H.icon?g.sz(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};e5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ym:H.card?g.sz(H.card):null,Fj:H.teaser?g.sz(H.teaser):null,sf:H.icon?g.sz(H.icon):null,LA:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:W4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},e5(c,e)}}else k2a(a.j,e);c=
!0}}c&&(E4(a.player),a.GD())},X2a=function(a,b){var c=!1;
a.j||(a.j=U2a(a),g.M(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(l2a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.xA(b.headerText):"",g.rh(c.Lb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.sz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.sz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.sf=b.icon.infoCardIconRenderer.trackingParams?
g.sz(b.icon.infoCardIconRenderer.trackingParams):null,E4(a.player),a.GD())},Y2a=function(a,b,c,d,e){if(!a.player.V().Sc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new W1a("openUrl","click",new U1a("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.xA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.xA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.xA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.xA(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.xA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.xA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new $1a(c,"branding","branding",f,d);l=N2a(a);a.u.element.appendChild(l);f=new l5(l,n5(a),f);f.zA();g.M(f,f);a.I[c]=f}},R2a=function(a,b){return function(){var c=
g.za.apply(0,arguments);
a.isDisposed()||a.S.push(g.Tn.Jh(function(){b.apply(null,g.t(c))}))}},Z2a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.uN.prototype.Rw=g.ba(17,function(a,b){var c=g.wO(this.wb());c&&c.Rw(a,b)});
var G4={},H4=null;g.Va(J4,g.ro);g.k=J4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Tc())return!1;I4(this);this.startTime=a=g.Ra();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.CD();this.bk("play");-1==this.j&&this.bk("resume");this.j=1;var b=g.Oa(this);b in G4||(G4[b]=this);z1a();A1a(this,a);return!0};
g.k.stop=function(a){I4(this);this.j=0;a&&(this.progress=1);B1a(this,this.progress);this.bk("stop");this.Vz()};
g.k.pause=function(){this.Tc()&&(I4(this),this.j=-1,this.bk("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.bk("destroy");J4.Re.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.tF=function(){this.bk("animate")};
g.k.bk=function(a){this.dispatchEvent(new C1a(a,this))};
g.Va(C1a,g.af);g.Va(K4,J4);K4.prototype.C=function(){};
K4.prototype.tF=function(){this.C();K4.Re.tF.call(this)};
K4.prototype.Vz=function(){this.C();K4.Re.Vz.call(this)};
K4.prototype.CD=function(){this.C();K4.Re.CD.call(this)};
g.Va(D1a,K4);D1a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var h5=new g.Xo("browseEndpoint");g.v(L4,g.J);L4.prototype.Ra=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.yx(a,b,c);this.j.push(a);return a};
L4.prototype.mD=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.Foa(a,b,c);this.j.push(a);return a};
L4.prototype.yc=function(a){g.zx(a);g.Xb(this.j,a)};
L4.prototype.ra=function(){g.zx(this.j);this.j.length=0;g.J.prototype.ra.call(this)};g.v(G1a,g.eO);g.k=G1a.prototype;g.k.load=function(){g.eO.prototype.load.call(this);if(!O4(this)){var a=g.UBa(this.player.getVideoData());a?(a=F1a(a,H1a(this)),P4(this,a,!1)):I1a(this)}};
g.k.unload=function(){P4(this,null);this.B&&(this.B.abort(),this.B=null);g.eO.prototype.unload.call(this)};
g.k.Bg=function(a,b){return O4(this)?"loadCustomEndscreenRenderer"===a?(a=F1a(b,"new"),P4(this,a),!0):null:null};
g.k.getOptions=function(){return O4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Cb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<$2a.length;f++){var h=Math.abs(b.width-$2a[f]);if(-1===e||d>=h)e=f,d=h}d=a3a[e];this.u&&g.zl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Jl(e.element,m,f);g.Fl(e.element,n,p);this.ea&&(g.io(e.element,b3a),256<m||256<f?g.fo(e.element,"ytp-ce-large-round"):96<m||96<f?g.fo(e.element,"ytp-ce-medium-round"):g.fo(e.element,"ytp-ce-small-round"));g.io(e.element,c3a);m=h.left+h.width/2;h=h.top+l/2;g.fo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.io(e.element,a3a);g.fo(e.element,d);(e=g.ah(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())T4(this,this.endscreen.impressionUrls),(a=g.zz())&&this.endscreen.visualElement&&g.Ez(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.fo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.fo(b,"ytp-ce-shown");T4(this,c.impressionUrls);(b=g.zz())&&g.Ez(b,c.visualElement);this.player.V().C&&this.player.Pa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.ho(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.ho(b,"ytp-ce-shown");this.player.V().C&&this.player.Pa("endscreenelementhidden",a)}};
g.k.O3=function(a){var b=this;a.target===window&&(new g.Xn(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.io(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var $2a=[346,426,470,506,570,640,853,1280,1920],a3a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),c3a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],b3a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var V1a={tla:"current",bIa:"new"};var X1a={CLOSE:"close",BLa:"openUrl",SUBSCRIBE:"subscribe"},Y1a={Cga:"click",CLOSE:"close",Pua:"hidden",LQa:"rollOut",MQa:"rollOver",ESa:"shown"};$1a.prototype.ye=function(){var a=a2a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var W2a={nca:"anchored",ZT:"branding",CHANNEL:"channel",ila:"cta",Sua:"highlightText",Eya:"label",PLAYLIST:"playlist",tOa:"popup",hVa:"speech",SUBSCRIBE:"subscribe",cYa:"title",VIDEO:"video",s3a:"website"},V2a={ZT:"branding",Dea:"card",una:"drawer",Rua:"highlight",eEa:"marker",tPa:"promotion",TEXT:"text",a4a:"widget"};g.v($4,g.J);g.k=$4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.qA(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.eb.set(a,e);this.context.G.qe([a])};
g.k.zA=function(){this.context.u.subscribe("resize",this.OB,this)};
g.k.uF=function(a,b,c,d,e,f){if(this.yb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.oh(this.element)};
g.k.OB=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=V4(a);if(f){var h=h2a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.lu(f||"");m&&n&&(n.v||n.list)?e.context.G.Nl(n.v,b,n.list,!1):g.iM(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m5(this.context.logger,c,l,d);g2a(f)||(c=g.zz(),d=b.itct,c&&d&&g.Jz(c,g.sz(d)))}};
g.k.ra=function(){this.Ya.clear();this.eb.clear();g.J.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.v(j2a,$4);g.k=j2a.prototype;g.k.Zp=function(){this.qa&&e5(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Kl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.OB=function(){var a=this.isAvailable();g.Ll(this.element,a);g.jo(this.context.G.getRootNode(),g.uT.IV_DRAWER_ENABLED,a);E4(this.G)};
g.k.destroy=function(){this.G.Rw(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Tx(this.ea);g.zx(this.ya);this.Wa&&this.Wa.dispose();this.D&&this.D.dispose();$4.prototype.destroy.call(this)};
g.k.sY=function(){if(this.B){m5(this.context.logger,j5(this).tracking.close);var a=g.zz();a&&this.J&&g.Jz(a,this.J);d5(this)}};
g.k.LY=function(){g.jo(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.E_=function(){var a=g.zz(),b=j5(this);b=b?b.sf:this.sf;a&&b&&g.Hz(a,[b])};
g.k.D_=function(){var a=g.zz(),b=j5(this);b=b?b.sf:this.sf;a&&b&&g.Iz(a,[b])};
g.k.CU=function(){var a=j5(this);m5(this.context.logger,a.tracking.SS);var b=g.zz();b&&a&&g.Hz(b,[a.Fj,a.sf])};
g.k.G_=function(){var a=g.zz(),b=j5(this);a&&b&&g.Iz(a,[b.Fj])};
g.k.BU=function(a){var b=j5(this),c=g.zz();this.j?a?(a=this.context.logger,m5(a,b.tracking.HE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Fj&&g.Jz(c,b.Fj)):(a=this.context.logger,m5(a,b.tracking.HE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.sf&&g.Jz(c,b.sf)):(a=this.context.logger,m5(a,b.tracking.HE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.sf&&g.Jz(c,this.sf))};g.v(k5,$4);k5.prototype.zA=function(){$4.prototype.zA.call(this);y2a(this)};
k5.prototype.show=function(){$4.prototype.show.call(this);var a=g.zz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Hz(a,[g.sz(b.itct)])};
k5.prototype.hide=function(){$4.prototype.hide.call(this);var a=g.zz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Iz(a,[g.sz(b.itct)])};g.v(l5,k5);
l5.prototype.show=function(){if(!this.isActive){k5.prototype.show.call(this);if(!this.J){g.fo(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Fa:["branding-img","iv-click-target"],X:{"aria-label":"Marca-d'\u00e1gua do canal",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ll(this.u,!1);var b=this.context.Y.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Fa:["branding-img-container"]}):this.createElement({F:"button",Fa:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.ye();c&&(b=this.context.Y.K("html5_player_branding_button_killswitch")?this.u:b,a5(this,b,c,this.annotation.id,a.session_data));C2a(this,a);this.J=!0}g.Ll(this.element,!0);this.isActive=!0;this.u&&z2a(this,this.u)}};
l5.prototype.hide=function(){this.isActive&&(k5.prototype.hide.call(this),g.Ll(this.element,!1),this.isActive=!1)};
l5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);k5.prototype.destroy.call(this)};g.v(E2a,k5);g.k=E2a.prototype;g.k.show=function(){this.isActive||(k5.prototype.show.call(this),this.Z||(G2a(this),this.Z=!0),g.Ll(this.element,!0),g.Mh(function(){g.ho(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,K2a(this),H2a(this),I2a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.fo(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.uF=function(a,b,c,d,e,f){return this.isCollapsed?!1:k5.prototype.uF.call(this,a,b,c,d,e,f)};
g.k.HZ=function(a){this.S=!0;F2a(this,500,a)};
g.k.GZ=function(){this.S=!1;J2a(this)};
g.k.BZ=function(a){a.stopPropagation();this.hide()};
g.k.CZ=function(a){a.stopPropagation();K2a(this);this.isCollapsed=!0;g.fo(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();k5.prototype.destroy.call(this)};g.v(M2a,g.eO);g.k=M2a.prototype;g.k.Bg=function(a,b){if(!Z2a(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.YXa(b))&&Q2a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(n2a(this.j,b),E4(this.player)),!0}return null};
g.k.getOptions=function(){return Z2a(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ot=function(){var a=this.player.V(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.JT||a.qa.get(b.videoId)||g.mI(b)||g.nI(b)?!0:!1};
g.k.GD=function(){if(this.B){var a=this.player.gb().getVideoContentRect(!0);g.Jl(this.B.element,a.width,a.height);g.Fl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.fk();a=this.j;b=b.width;g.jo(a.C,"iv-drawer-small",426>=b);g.jo(a.C,"iv-drawer-big",1280<=b)}};
g.k.DU=function(a){O2a(this,a.state);g.V(a.state,2)&&(this.Ai()&&this.xm()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Rw(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.uu(h)&&h.responseXML?h.responseXML:null)&&(Q2a(b,h),g.fo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.eO.prototype.load.call(this);O2a(this,this.player.Eb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Dv()&&(a=R2a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().qa.get(d);f&&S2a(e,f);f=f&&(f.UB||f.jy);if(!c.Zt||f)c.Ya?this.C=g.Au(c.Ya,e):(this.Gn=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Gn));
g.BN(this.player,this.B.element,4);this.GD();(f=g.mI(c))&&X2a(this,f);(f=g.nI(c))&&f.featuredChannel&&Y2a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ya&&(this.Gn&&(this.player.removeEventListener("videodatachange",this.Gn),this.Gn=null),this.C=g.Au(b.Ya,a))};
g.k.unload=function(){this.player.Gf("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,E4(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.eO.prototype.unload.call(this);this.B.detach();this.Gn&&(this.player.removeEventListener("videodatachange",this.Gn),this.Gn=null)};
g.k.CR=function(a){a===this.player.getVideoData().videoId&&(this.loaded?T2a(this):this.load())};
g.k.Ai=function(){return!!this.j&&this.j.isAvailable()};
g.k.xm=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ai();this.j&&(a?c?c5(this.j,c,b):c5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):d5(this.j))};
g.k.Rw=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().qa.unsubscribe("vast_info_card_add",this.CR,this);g.ho(this.player.getRootNode(),g.uT.IV_DRAWER_OPEN);for(var a=this.S,b=g.Tn,c=0,d=a.length;c<d;c++)b.Zk(a[c]);this.S.length=0;g.eO.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.dO("annotations_module",M2a);g.dO("creatorendscreen",G1a);})(_yt_player);
